-- Active: 1777208460017@@127.0.0.1@3306@Mysql_Learners

-- EXERCISE 1: RETRIEVE_ALL PROCEDURE
CALL RETRIEVE_ALL;

DROP PROCEDURE RETRIEVE_ALL;

CALL RETRIEVE_ALL;

-- EXERCISE 2: UPDATE_SALEPRICE
CALL RETRIEVE_ALL;
CALL UPDATE_SALEPRICE(1,'BAD');
CALL RETRIEVE_ALL;
CALL `UPDATE_SALEPRICE`(3,'WORSE');
CALL `RETRIEVE_ALL`;