-- Active: 1777208460017@@127.0.0.1@3306@HR
SELECT * FROM `EMPLOYEES`;

-- Task 1: Create a View
CREATE VIEW EMPSALARY AS
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, SALARY
FROM EMPLOYEES;
SELECT * FROM EMPSALARY;

-- Task 2: Update a View
CREATE OR REPLACE VIEW EMPSALARY AS
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, JOB_TITLE,
MIN_SALARY, MAX_SALARY
FROM EMPLOYEES, JOBS
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_ID;
SELECT * FROM EMPSALARY;

-- Task 3: Drop a View
DROP VIEW EMPSALARY;
SELECT * FROM EMPSALARY;

/* PRACTICE PROBLEMS
1. Create a view “EMP_DEPT” which has the following information.
EMP_ID, FNAME, LNAME and DEP_ID from EMPLOYEES table
*/
CREATE VIEW EMP_DEPT AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_ID FROM EMPLOYEES;
SELECT * FROM EMP_DEPT;

/*
2. Modify “EMP_DEPT” such that it displays Department names instead of Department IDs. For this, we need to combine information from EMPLOYEES and DEPARTMENTS as follows.
EMP_ID, FNAME, LNAME from EMPLOYEES table and
DEP_NAME from DEPARTMENTS table, combined over the columns DEP_ID and DEPT_ID_DEP.
*/
CREATE OR REPLACE VIEW EMP_DEPT AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEP_ID = DEPARTMENTS.DEP_ID;
SELECT * FROM EMP_DEPT;

/*
3. Drop the view “EPM_DEPT”.
*/
DROP VIEW EMP_DEPT;