-- Active: 1777208460017@@127.0.0.1@3306@Mysql_Learners
CREATE PROCEDURE RETRIEVE_ALL()
BEGIN
    SELECT * FROM PETSALE;
END;

CREATE PROCEDURE UPDATE_SALEPRICE(IN ANIMAL_ID INTEGER, IN ANIMAL_HEALTH VARCHAR(5))
BEGIN
    -- For animal with ID XX having BAD health condition, the sale price will be reduced further by 25%.
    IF ANIMAL_HEALTH = 'BAD' THEN
        UPDATE `PETSALE`
        SET `SALEPRICE` = `SALEPRICE` * 0.75
        WHERE ID = ANIMAL_ID;
    -- For animal with ID YY having WORSE health condition, the sale price will be reduced further by 50%.
    ELSEIF ANIMAL_HEALTH = 'WORSE' THEN
        UPDATE `PETSALE`
        SET `SALEPRICE` = `SALEPRICE` * 0.50
        WHERE ID = ANIMAL_ID;
    ELSE
        UPDATE `PETSALE`
        SET `SALEPRICE` = `SALEPRICE`
        WHERE ID = ANIMAL_ID;
    END IF;
END;

-- Active: 1777208460017@@127.0.0.1@3306@Mysql_Learners

-- EXERCISE 1: RETRIEVE_ALL PROCEDURE
CALL RETRIEVE_ALL;

DROP PROCEDURE RETRIEVE_ALL;

CALL RETRIEVE_ALL;

-- EXERCISE 2: UPDATE_SALEPRICE
CALL RETRIEVE_ALL;
CALL UPDATE_SALEPRICE(1,'BAD');
CALL RETRIEVE_ALL;
CALL `UPDATE_SALEPRICE`(3,'WORSE');
CALL `RETRIEVE_ALL`;