-- Active: 1777208460017@@127.0.0.1@3306@HR
CREATE DATABASE HR;

CREATE TABLE EMPLOYEES (
    EMP_ID CHAR(9) NOT NULL,
    F_NAME VARCHAR(15) NOT NULL,
    L_NAME VARCHAR(15) NOT NULL,
    SSN CHAR(6),
    B_DATE DATE,
    SEX CHAR(1),
    ADDRESS VARCHAR(30),
    JOB_ID CHAR(9) NOT NULL,
    SALARY INTEGER,
    MANAGER_ID CHAR(9) NOT NULL,
    DEP_ID CHAR(9) NOT NULL,
    PRIMARY KEY (EMP_ID)
);

CREATE TABLE JOB_HISTORY (
    EMP_ID CHAR(9) NOT NULL,
    START_DATE DATE,
    JOB_ID CHAR(9) NOT NULL,
    DEP_ID CHAR(9) NOT NULL
);

CREATE TABLE JOBS (
    JOB_ID CHAR(9) NOT NULL,
    JOB_TITLE VARCHAR(50),
    MIN_SALARY INTEGER,
    MAX_SALARY INTEGER,
    PRIMARY KEY (JOB_ID)
);

CREATE TABLE DEPARTMENTS (
    DEP_ID CHAR(9) NOT NULL,
    DEP_NAME VARCHAR(30),
    MANAGER_ID CHAR(9) NOT NULL,
    LOC_ID CHAR(9) NOT NULL,
    PRIMARY KEY (DEP_ID)
);

CREATE TABLE LOCATIONS (
    LOC_ID CHAR(9) NOT NULL,
    DEP_ID CHAR(9) NOT NULL,
    PRIMARY KEY (LOC_ID, DEP_ID)
);